### PR TITLE
Replace "lodash.pick" with "lodash/pick"

### PR DESCRIPTION
**Pull request by dangowans**
The two packages function the same.
Clears up https://github.com/advisories/GHSA-p6mc-m468-83gw

### CODE REVIEW

**Comment by pimterry** [comment]
Hmm, interesting, yes... It's not an impactful vulnerability, but yes it would be nice to drop that warning.

What about if we just drop the per-method dependencies entirely, depend on lodash directly and import from subpaths there instead? Like `require('lodash/pick')`. That's the recommended approach and those per-method packages are actually deprecated because the space savings are apparently rarely worthwhile & could be counterproductive in reality (see https://lodash.com/per-method-packages - presumably this is why they're not being updated).

**Comment by dangowans** [comment]
That works for me. I updated the pull request with `lodash` instead.

**Comment by pimterry** [comment]
Nice stuff, thanks @dangowans! I'll release as v2.2.1 in just a sec.

**Comment by dangowans** [comment]
Thanks. I see there was more lodash packages than just the one I was looking at. Good update!

**Pull request merged**
